modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/MC-U-Team/Enhanced-Anvil/issues"
license="Apache-2.0 License"

[[mods]]
	modId="enhancedanvil"
	version="${file.jarVersion}"
	displayName="Enhanced Anvil"
	displayURL="https://u-team.info/mods/enhancedanvil"
	updateJSONURL="https://api.u-team.info/update/enhancedanvil.json"
	logoFile="logo.png"
	credits="Team U-Team"
	authors="HyCraftHD"
	description="Join our discord server here: https://discord.hycrafthd.net\n\nThis mod adds a new anvil to the game that removes the 'Too Expensive' limit restriction but is still not overpowered."
	
	[[dependencies.enhancedanvil]]
	    modId="forge"
	    mandatory=true
	    versionRange="[47.0.35,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.enhancedanvil]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.20.1]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.enhancedanvil]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[5.1.3.267,)"
	    ordering="NONE"
	    side="BOTH"